# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StripeSDK-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StripeSDK-Demo
  pod 'StripeTerminal'

  target 'StripeSDK-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
